"""empty message

Revision ID: 0e0e84737d61
Revises: 622d00292ccc
Create Date: 2019-09-16 19:11:02.238210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e0e84737d61'
down_revision = '622d00292ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('img',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('img', sa.LargeBinary(), nullable=False),
    sa.Column('img_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('img')
    # ### end Alembic commands ###
