"""empty message

Revision ID: 5a3b9df44183
Revises: b27cf8d497d0
Create Date: 2019-09-16 18:52:40.687488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a3b9df44183'
down_revision = 'b27cf8d497d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('img', 'img_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('img', 'img_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
