"""empty message

Revision ID: b27cf8d497d0
Revises: a3ac21bc30e5
Create Date: 2019-09-16 18:22:45.375902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27cf8d497d0'
down_revision = 'a3ac21bc30e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('img',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('img', sa.BLOB(), nullable=False),
    sa.Column('img_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('img')
    # ### end Alembic commands ###
