"""empty message

Revision ID: dcf5ae7641bb
Revises: 61bb152d0d5e
Create Date: 2019-06-27 17:52:32.377401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dcf5ae7641bb'
down_revision = '61bb152d0d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=128), nullable=False))
    op.drop_column('users', '_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_password', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
